server: 
  port: 6001
spring: 
  application: 
    name: zuul-server #eureka 服务端的实例名称
eureka: 
  client:
    # 是否向服务注册中心注册自己  如果本身是eureka服务则不用注册自己
    register-with-eureka: true
    #是否检索eureka上的服务   如果是服务的消费者才会设置为true 从eureka上获取服务以便调用服务
    fetch-registry: true
    service-url: #特别注意  不要写成serverUrl否则不认,使用localhost:8761/eureka作为服务注册中心
      # 服务注册中心的配置内容，指定服务注册中心的位置 eureka注册中心服务器地址
      defaultZone: http://127.0.0.1:7001/eureka

## 路由
zuul:
  routes:
    eureka-client-hello-provider: # 服务的server-id
      path: /cloud/**
      service-id: EUREKA-CLIENT-HELLO-CONSUMER  # 根据eureka服务id解析ip后转发请求
      # url: http://127.0.0.1:9001/
    baidu: # 服务的server-id
      path: /baidu/**
      # service-id: EUREKA-CLIENT-HELLO-CONSUMER
      url: https://www.baidu.com/ # 直接将请求转发到某url上


# zuul 整合了hystrix ,可以定义超时时间
hystrix:
  command:
    default: # default 是feign的全局超时熔断设置
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  # 如果加入了zuul 则超时会报500错误
